apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-user
  namespace: elbaph          # Changed from argocd
  labels:
    app: loki                # Fixed label syntax
data:
  accounts.dev-user: apiKey, login
  accounts.dev-user.enabled: "true"
  accounts.dev-user.password: ""
