apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-cm
  namespace: elpbaph
  labels:
    app: loki   # Corrected from 'labels: loki'
data:
  index.html: |
    <h1>Vous etes sur l'ile d'ElBaph via le pod Loki </h1>
